package dev.flowgraph.service

import com.intellij.openapi.components.Service
import com.intellij.openapi.project.Project
import dev.flowgraph.model.FlowGraph
import dev.flowgraph.model.NodeKind
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.util.concurrent.CopyOnWriteArrayList

/**
 * Holds the latest semantic graph and exports StateFlow runtime keys discovered by the Analysis API.
 * In v0.11 global instrumentation mode `.flowgraph/targets.txt` is metadata only: the debug APK is
 * already instrumented for all eligible Flow-state fields, so selecting another existing Flow does
 * not require rebuilding.
 */
@Service(Service.Level.PROJECT)
class FlowGraphProjectService(private val project: Project) {
    @Volatile
    var latestGraph: FlowGraph? = null
        private set

    @Volatile
    var lastTargetsFile: Path? = null
        private set

    private val listeners = CopyOnWriteArrayList<(FlowGraph) -> Unit>()

    fun publish(graph: FlowGraph) {
        latestGraph = graph
        exportRuntimeTargets(graph)
        listeners.forEach { it(graph) }
    }

    fun addListener(listener: (FlowGraph) -> Unit) {
        listeners += listener
        latestGraph?.let(listener)
    }

    private fun exportRuntimeTargets(graph: FlowGraph) {
        val base = project.basePath ?: return
        val targets = graph.nodes.asSequence()
            .filter { it.kind == NodeKind.STATE }
            .mapNotNull { it.runtimeKey?.trim()?.takeIf(String::isNotEmpty) }
            .distinct()
            .sorted()
            .toList()
        if (targets.isEmpty()) return

        runCatching {
            val dir = Path.of(base, ".flowgraph")
            Files.createDirectories(dir)
            val targetFile = dir.resolve("targets.txt")
            val contents = buildString {
                appendLine("# Generated by Flow Graph v0.12.6. Safe to commit-ignore.")
                appendLine("# Analysis-API runtime keys for the currently published graph.")
                appendLine("# Metadata only in default global instrumentation mode; does not gate debug APK instrumentation.")
                targets.forEach(::appendLine)
            }
            Files.writeString(
                targetFile,
                contents,
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING,
                StandardOpenOption.WRITE,
            )
            lastTargetsFile = targetFile
        }
    }
}
